### ISSUE TITLE
SSL for additional security.

### ISSUE THREAD

**Issue by praisethemoon** [mahdCompany/fnl-website#3]
Hello,

This is such a lovely website, well done. However, I think it is insecure since the signup form contain user sensitive/personal information. I suggest switching to https ASAP.

Cheers.

**Comment by elacheche** [comment]
@dardourimohamed You can use a FREE Let's Encrypt SSL cert, then you need to redirect all 80 requests (nginx conf file) to 443, don't forget to use sed or a sql query to change all http to https in the DB (one of reasons why WP sucks)..

**Comment by dardourimohamed** [comment]
https://fnl.tn
https://www.fnl.tn
